Created index.html; added markup for navigation bar and hero section,…
GiftedNathan/portfolio pull request #1
Opened 2022-12-01 19:29 UTC by GiftedNathan

Created index.html; added markup for navigation bar and hero section,
Created style.css; added styling for navigation bar and hero section.
Added and configured linters for HTML&CSS.

2022-12-01 20:00 UTC, tugsem requested changes
## Invalid Code Review Request ❌ 

Hi @GiftedNathan , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<h1>You have submitted a project, that doesn't have a readme file.</h2>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-01 21:11 UTC, GiftedNathan commented
Thank you @tugsem for your review. it was an oversight. However, I have made the required adjustment.

2022-12-01 22:25 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @GiftedNathan 👋 , 
![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-01 22:25 UTC, abdulhamiid commented on index.html
> +        </header>
- [ ]  👍 Your design is Great!, but you still need to make a few changes 😊

- [ ] Your design 👇 
![nathanToolbar](https://user-images.githubusercontent.com/78251927/205166778-b4c366d1-2990-4096-a079-6c23190ebf92.PNG)

- [ ] Figma design 👇 
![header](https://user-images.githubusercontent.com/78251927/205162641-a69ab7db-dcc2-4249-ae74-9e59444e3878.PNG)

- [ ] The Hamburger menu is missing, please kindly fix that.

- [ ] As per the [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md), it is mentioned that you must stick to the design as much as possible (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). 

- [ ]  Please kindly correct the Logo font to match the font in the template.

- [ ] Logo 👇 
```
<span class="logo">Nathan</span>
```
Please kindly place the logo in an `<a>` tag, as it is meant to be a link.

- [ ] Hamburger 👇 
```
<button class="menu-button">
    <img src="/images/menu.png" alt="">
</button>
```
Let us wrap the hamburger button inside a `nav` tag. The nav tag is for semantics reasons and user experience for mobile devices. you can learn more [here](https://html.com/tags/nav/)

2022-12-01 22:25 UTC, abdulhamiid commented on index.html
> +                </div>
Your design 👇 
![nathanSocial](https://user-images.githubusercontent.com/78251927/205170039-cfe5afa7-aeaf-43a7-a67c-80631b782fcd.PNG)

Figma design 👇 
![Figma social](https://user-images.githubusercontent.com/78251927/205170112-b207dffc-34a8-4e80-a57d-0c0e21d99ad0.PNG)

- [ ] Please kindly arrange the icons the way they appear in the Figma design, and also let's include the missing icon. (you have added four icons instead of five, the `linked icon` is missing) 😊, please kindly fix that.

- [ ]  Kindly ensure the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag).

- [ ] **[OPTIONAL]** Please kindly consider using the `alt` attribute to describe each image e.g `<img src="./images/github.png" alt="Github icon">`, this way, it will be semantically correct and the screen readers and other technologies will thank you.

2022-12-01 22:25 UTC, abdulhamiid commented on index.html
> +        <section class="hero">
- [ ] As per the [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md), please kindly align the content of this section with flexbox

2022-12-01 22:25 UTC, abdulhamiid commented on index.html
> +            </p>
Your design 👇 
![main11](https://user-images.githubusercontent.com/78251927/205169241-b00ef224-57e4-4c81-90d0-e244e030cb99.PNG)

Figma design 👇 
![main22](https://user-images.githubusercontent.com/78251927/205169296-d0f2c090-7627-4b72-80e2-5e84ae50b11e.PNG)

- [ ] Please kindly correct the font to match the font in the template

2022-12-01 22:43 UTC, GiftedNathan commented on index.html
> +            </p>
Thanks for your reviews. I will act accordingly.

2022-12-02 10:23 UTC, Alfredbis29 approved these changes
# STATUS: APPROVED  
 ## Hi @GiftedNathan ,
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Your repo is professional :white_check_mark:
 * Well structured files :white_check_mark:
 * No Linter errors :white_check_mark:
 
 Now you can merge this branch and move on :1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers four_leaf_clover:

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions
- [ ] Check under the review :point_down:  :upside_down_face: 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 10:23 UTC, Alfredbis29 commented on index.html
> +                <p>LET’S connect</p>
- [ OPTIONAL] It could be much better if your subtitle  uses a `header` tag hx (examples: h1,h2,h3, etc...), kindly use `h` instead of `p` for Html sematic reason :wink:

2022-12-02 10:40 UTC, GiftedNathan commented on index.html
> +                <p>LET’S connect</p>
Thanks for this review

2022-12-02 10:45 UTC, merged